version: '3.8'

services:
  docs:
    build:
      context: ./apps/docs
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ../../:/app
      - turborepo-cache:/app/.turbo
    environment:
      - NODE_ENV=development

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../../:/app
      - turborepo-cache:/app/.turbo
    environment:
      - NODE_ENV=development

volumes:
  turborepo-cache:
    driver: local